 # -*- coding: utf-8 -*-
from __future__ import division
from GameBase import GameBase
import pygame as pg, random

class Questions(GameBase):
    def __init__(self, data, surface):
        super().__init__(data, surface)
        self.Scattered_Questions = (
            {'Q': r'sin^2(x)+cos^2(x) = ?', 'A': r'1', 'W_As': ('0', '2', '-1')}, 
            {'Q': r'cos(Θ)+i*sin(Θ) = ?', 'A': r'e^(i*Θ)', 'W_As': (r'-1', r'e^(i*π)', r'e^(i*π)+1')},
            {'Q': r'sin^k(x)*sin(k*x)+cos^k(x)*cos(k*x)=cos^k(2x), x∈R, k=?', 'A': r'3', 'W_As': (r'4', r'5', r'6')}, 
            {'Q': r'cosA*cosB-sinA*sinB = ?', 'A': r'cos(A+B)', 'W_As': (r'cos(A-B)', r'sin(A+B)', r'sin(A-B)')}, 
            {'Q': r'cosA*cosB+sinA*sinB = ?', 'A': r'cos(A-B)', 'W_As': (r'cos(A+B)', r'sin(A+B)', r'sin(A-B)')}, 
            {'Q': r'sinA*cosB+cosA*sinB = ?', 'A': r'sin(A+B)', 'W_As': (r'cos(A+B)', r'cos(A-B)', r'sin(A-B)')}, 
            {'Q': r'sinA*cosB-cosA*sinB = ?', 'A': r'sin(A-B)', 'W_As': (r'cos(A+B)', r'sin(A+B)', r'cos(A-B)')}, 
            {'Q': r'(tanA+tanB)/(1-tanA*tanB) = ?', 'A': r'tan(A+B)', 'W_As': (r'tan(A-B)', r'tan(A*B)', r'tan(B-A)')}, 
            {'Q': r'(tanA-tanB)/(1+tanA*tanB) = ?', 'A': r'tan(A-B)', 'W_As': (r'tan(A+B)', r'tan(A*B)', r'tan(B-A)')}, 
            {'Q': r'(1/2)*[sin(A+B)+sin(A-B)] = ?', 'A': r'sinA*cosB', 'W_As': (r'cosA*sinB', r'cosA*cosB', r'sinA*sinB')}, 
            {'Q': r'(1/2)*[sin(A+B)-sin(A-B)] = ?', 'A': r'cosA*sinB', 'W_As': (r'sinA*cosB', r'cosA*cosB', r'sinA*sinB')}, 
            {'Q': r'(1/2)*[cos(A+B)+cos(A-B)] = ?', 'A': r'cosA*cosB', 'W_As': (r'cosA*sinB', r'sinA*cosB', r'sinA*sinB')}, 
            {'Q': r'(1/2)*[cos(A+B)-cos(A-B)] = ?', 'A': r'sinA*sinB', 'W_As': (r'cosA*sinB', r'cosA*cosB', r'sinA*cosB')}, 
            {'Q': r'sin(A+B)+sin(A-B) = ?', 'A': r'2*sinA*cosB', 'W_As': (r'2*cosA*sinB', r'2*cosA*cosB', r'2*sinA*sinB')}, 
            {'Q': r'sin(A+B)-sin(A-B) = ?', 'A': r'2*cosA*sinB', 'W_As': (r'2*sinA*cosB', r'2*cosA*cosB', r'2*sinA*sinB')}, 
            {'Q': r'cos(A+B)+cos(A-B) = ?', 'A': r'2*cosA*cosB', 'W_As': (r'2*cosA*sinB', r'2*sinA*cosB', r'2*sinA*sinB')}, 
            {'Q': r'cos(A+B)-cos(A-B) = ?', 'A': r'2*sinA*sinB', 'W_As': (r'2*cosA*sinB', r'2*cosA*cosB', r'2*sinA*cosB')}, 
            {'Q': r'sinA+sinB = ?', 'A': r'2*sin((A+B)/2)*cos((A-B)/2)', 'W_As': (r'2*cos((A+B)/2)*sin((A-B)/2)', r'2*cos((A+B)/2)*cos((A-B)/2)', r'-2*sin((A+B)/2)*sin((A-B)/2)')}, 
            {'Q': r'sinA-sinB = ?', 'A': r'2*cos((A+B)/2)*sin((A-B)/2)', 'W_As': (r'2*sin((A+B)/2)*cos((A-B)/2)', r'2*cos((A+B)/2)*cos((A-B)/2)', r'-2*sin((A+B)/2)*sin((A-B)/2)')}, 
            {'Q': r'cosA+cosB = ?', 'A': r'2*cos((A+B)/2)*cos((A-B)/2)', 'W_As': (r'2*sin((A+B)/2)*cos((A-B)/2)', r'2*cos((A+B)/2)*sin((A-B)/2)', r'-2*sin((A+B)/2)*sin((A-B)/2)')}, 
            {'Q': r'cosA-cosB = ?', 'A': r'-2*sin((A+B)/2)*sin((A-B)/2)', 'W_As': (r'2*sin((A+B)/2)*cos((A-B)/2)', r'2*cos((A+B)/2)*sin((A-B)/2)', r'2*cos((A+B)/2)*cos((A-B)/2)')}, 
            {'Q': r'2*sin((A+B)/2)*cos((A-B)/2) = ?', 'A': r'sinA+sinB', 'W_As': (r'sinA-sinB', r'cosA+cosB', r'cosA-cosB')}, 
            {'Q': r'2*cos((A+B)/2)*sin((A-B)/2) = ?', 'A': r'sinA-sinB', 'W_As': (r'sinA+sinB', r'cosA+cosB', r'cosA-cosB')}, 
            {'Q': r'2*cos((A+B)/2)*cos((A-B)/2) = ?', 'A': r'cosA+cosB', 'W_As': (r'sinA+sinB', r'sinA-sinB', r'cosA-cosB')}, 
            {'Q': r'-2*sin((A+B)/2)*sin((A-B)/2) = ?', 'A': r'cosA-cosB', 'W_As': (r'sinA+sinB', r'sinA-sinB', r'cosA+cosB')}, 
            {'Q': r'→a ⊥ →b <=> ?', 'A': r'→a * →b = 0', 'W_As': (r'→a • →b = 1', r'→a • →b = -1', r'→a • →b = i')}, 
            {'Q': r'|→a|=1, |→b|=1, |→a + →b|=1, |→a - →b| = ?', 'A': r'3^(1/2)', 'W_As': (r'1', r'0', r'2^(1/2)')}, 
            {'Q': r'A={1, x, x^2-x},B={1, 2, x}, A = B, x = ?', 'A': r'x = -1', 'W_As': (r'x = -(1/2)', r'x = 0', r'x = 1')}, 
            {'Q': r'A={x|2 ≤ x< 4},B={x|3x-7 ≥ 8-2x}, A ∪ B = ?', 'A': r'{x|x ≥ 2}', 'W_As': (r'{x|x ≥ 3}', r'{x|2 ≤ x < 3}', r'{x|x ≥ 4}')}, 
            {'Q': r'A={-4, 2a-1, a^2}, B={a-5, 1-a, 9}, A∩B={9}, a = ?', 'A': r'a = -3', 'W_As': (r'a = 3', r'a = -5', r'a = 5', )}, 
            {'Q': r'A={0, 2, a}, B={1, a^2}, A ∪ B = {0,1,2,4,16}, a = ?', 'A': r'a=4', 'W_As': ('0', '1', '2')}, 
            {'Q': r'A={x|x > 0},B={x|-1 ≤ x ≤ 2},A ∪ B = ?', 'A': r'{x|x≥-1}', 'W_As': (r'{x|x ≤ 2}', r'{x|0 < x ≤ 2}', r'{x|-1 ≤ x ≤ 2}')}, 
            {'Q': r'A={x|1 ≤ x < 4}, B={x|x < a}, A ⊆ B, a= ?', 'A': r'{a|a≥4}', 'W_As': (r'{a|a=4}', r'{a|a≤4}', r'{a|a<1}', )}, 
            {'Q': r'A={x, y}, B={0, x^2}, A=B, x=?, y=?', 'A': r'x=1,y=0', 'W_As': (r'x=0,y=1', r'x=1,y=1', r'x=0,y=0', )}, 
            {'Q': r'A={a^2＋2a-3, 2, 3}, B = {2,|a＋3|}, 5 ∈ A, 5 ∉ B, a=?', 'A': r'a=-4', 'W_As': (r'a=4', r'a=-3', r'a=-1')}, 
            {'Q': r'S={x|2x＋1 > 0},T={x|3x-5 < 0}, S ∩ T=?', 'A': r'{x|-(1/2) < x < (5/3)}', 'W_As': (r'Ø', r'{x|x < -(1/2)}', r'{x|x > (5/3)}')}, 
            {'Q': self.data.language['Posterior probability']+': '+r' P(A|B) = ?', 'A': r'(P(A)*P(B|A))/P(B)', 'W_As': (r'(P(A)*P(B|A))/P(A)', r'(P(B)*P(B|A))/P(B)', r'(P(B)*P(A|B))/P(A)')}, 
            # 极限
            {'Q': r'f(x)=(x^2+2*x)/(2*(x^2)+1), (x→∞)lim f(x)=?', 'A': r'1/2', 'W_As': (r'2', r'1', r'0')}, 
            {'Q': r'f(x)=x*((x^2+2)^(1/2)-x), (x→∞)lim f(x)=?', 'A': r'1', 'W_As': (r'0', r'∞', r'-1')}, 
            {'Q': r'f(x)=(1+1/x)^x, (x→∞)lim f(x)=?', 'A': r'e', 'W_As': (r'1', r'∞', r'1/e')}, 
            {'Q': r'f(x)=x/((x!)^(1/x)), (x→∞)lim f(x)=?', 'A': r'e', 'W_As': (r'1/e', r'1', r'∞')}, 
            {'Q': r'f(x)=(1+x)^(1/x), (x→0)lim f(x)=?', 'A': r'e', 'W_As': (r'1/e', r'∞', r'1')}, 
            {'Q': r'f(x)=sin(k*x)/(m*x), k,m∈R,m≠0, (x→0)lim f(x)=?', 'A': r'k/m', 'W_As': (r'-k/m', r'm/k', r'-m/k')}, 
            {'Q': r'f(x)=(e^x)/x, (x→0)lim f(x)=?', 'A': r'∞', 'W_As': (r'0', r'1', r'e')}, 
            {'Q': r'f(x)=(1-1/x)^x, (x→∞)lim f(x)=?', 'A': r'1/e', 'W_As': (r'e', r'1', r'∞')}, 
            {'Q': r'f(x)=arctan(x)/ln(x+1), (x→∞)lim f(x)=?', 'A': r'0', 'W_As': (r'1', r'∞', r'π')}, 
            {'Q': r'f(x)=(5*(x^2)+4)/(x^3+2*x), (x→∞)lim f(x)=?', 'A': r'0', 'W_As': (r'∞', r'1', r'5/3')}, 
            {'Q': r'f(x)=(3*(x^4)+2*x)/(x^3+2), (x→∞)lim f(x)=?', 'A': r'∞', 'W_As': (r'3', r'1', r'0')}, 
            {'Q': r'f(x)=(k*(x^2)+x)/(m*(x^2)+2), k,m∈R k,m≠0 (x→∞)lim f(x)=?', 'A': r'k/m', 'W_As': (r'm/k', r'k-m', r'k*m')}, 
            {'Q': r'(x→a)lim f(x)=k≠0, a,k∈R, (x→a)lim 1/f(x)=?', 'A': r'1/k', 'W_As': (r'0', r'1/a', r'k')}, 
            {'Q': r'f(x)=((1-cos(x))/sin(x))*(π-x), (x→π)lim f(x)=?', 'A': r'2', 'W_As': (r'1', r'0', r'π')},
            {'Q': r'f(x)=((k+n*x)/(m+n*x))^x, k,m,n∈R, n≠0, (x→∞)lim f(x)=?', 'A': r'(e^(k/n))*(e^(-m/n))', 'W_As': (r'(e^(k/n))*(e^(m/n))', r'1', r'0')}, 
            {'Q': r'f(x)=(1-k/x)^(x/m), k,m∈R, m≠0, (x→∞)lim f(x)=?', 'A': r'e^(-k/m)', 'W_As': (r'e^(k/m)', r'e^(-m/k)', r'e^(m/k)')}, 
            {'Q': r'f(x)=((1+k*x)^m-n)/x, k,m,n∈R, (x→0)lim f(x)=?', 'A': r'-∞*((n-1)/|n-1|)', 'W_As': (r'-∞*(n/|n|)', r'+∞*((n-1)/|n-1|)', r'+∞*(n/|n|)')}, 
            {'Q': r'f(x)=2^x/(1+2^x), (x→∞)lim f(x)=?', 'A': r'1', 'W_As': (r'∞', r'0', r'1/2')}, 
            {'Q': r'f(x)=(x+sin(x))/(x-cos(x)), (x→∞)lim f(x)=?', 'A': r'1', 'W_As': (r'∞', r'0', r'tan(x)')}, 
            {'Q': r'f(x)=(k^x-x^m)/(x-k), k,m∈R, (x→k)lim f(x)=?', 'A': r'+∞*(k^k-k^m)/|k^k-k^m|', 'W_As': (r'0', r'1', r'-∞*(k^k-k^m)/|k^k-k^m|')}, 
            {'Q': r'f(x)=x^(x/(1-x)), (x→1)lim f(x)=?', 'A': r'1/e', 'W_As': (r'e', r'1', r'0')}, 
            {'Q': r'f(x)=(ln(k+1/x)/ln(k))^x, k∈R, (x→∞)lim f(x)=?', 'A': r'e^(1/(k*ln(k)))', 'W_As': (r'1', r'∞', r'e^k')}, 
            {'Q': r'f(x)=x*((x^m+1)^k-(x^m-1)^k), k,m∈R, k,m>0, (x→+∞)lim f(x)=?', 'A': r'+∞', 'W_As': (r'-∞', r'0', r'1')}, 
            {'Q': r'f(x)=e^x-cos(x), (x→0)lim f(x)=?', 'A': r'0', 'W_As': (r'1', r'e', r'∞')}, 
            {'Q': r'f(x)=(1+1/x)^(x^2)/e^x, (x→∞)lim f(x)=?', 'A': r'e^(-1/2)', 'W_As': (r'e^(1/2)', r'e', r'1/e')}, 
            {'Q': r'f(x)=((1+x^2)*(1-cos2x)-2*(x^2))/x^4, (x→0)lim f(x)=?', 'A': r'4/3', 'W_As': (r'3/2', r'1/2', r'2')}, 
            {'Q': r'f(x)=e^x/((1+1/x)^(x^2))', 'A': r'e^(1/2)', 'W_As': (r'e', r'e^(-1/2)', r'1/e')}, 
            {'Q': r'f(x)=(4*(x^2)-8*x+5)^(1/2)+2*x+1, (x→-∞)lim f(x)=?', 'A': r'3', 'W_As': (r'2', r'1', r'∞')}, 
            {'Q': r'f(x)=(x+(x+x^(1/2))^(1/2))^(1/2)/(x+1)^(1/2), (x→+∞)lim f(x)=?', 'A': r'1', 'W_As': (r'0', r'∞', r'2')}, 
            {'Q': r'f(x)=sin(k*x)/(m*x), k,m∈R,m≠0, (x→π)lim f(x)=?', 'A': r'(k/m)*((-1)^(k-m))', 'W_As': (r'(k/m)', r'(m/k)*((-1)^(k-m))', r'1')}, 
            {'Q': r'f(x)=((1+x)^(1/k)-1)/x, k∈R, (x→0)lim f(x)=?', 'A': r'1/k', 'W_As': (r'k', r'k^(1/2)', r'1')}, 
            {'Q': r'f(x)=x/((1-cos^(1/2)(x)), (x→+0)lim f(x)=?', 'A': r'2^(1/2)', 'W_As': (r'2', r'1', r'0')}, 
            {'Q': r'f(x)=(x^3/(2*(x^2)-1)-x^2/(2*x+1)), (x→∞)lim f(x)=?', 'A': r'1/4', 'W_As': (r'3/4', r'1', r'0')}, 
            {'Q': r'f(x)=(x*(2*x-1)*(x+2))/(8*(x^3)+3*(x^2)), (x→∞)lim f(x)=?', 'A': r'1/4', 'W_As': (r'1/2', r'∞', r'2')}, 
            {'Q': r'f(x)=(1/(1-x))-(3/(1-x^3)), (x→1)lim f(x)=?', 'A': r'-1', 'W_As': (r'1', r'0', r'∞')}, 
            {'Q': r'f(x)=(x^3/(2*(x^2)-1))-(x^2/(2*x+1)), (x→∞)lim f(x)=?', 'A': r'1/4', 'W_As': (r'-1/4', r'4', r'2')}, 
            {'Q': r'f(x)=(a/(1-x)-b/(1-x^2)), (x→1)lim f(x)=1, a=?,b=?', 'A': r'a=-2, b=4', 'W_As': (r'a=2, b=4', r'a=2, b=-4', r'a=4, b=-2')}, 
            {'Q': r'f(x)=(1/(x^2-3*x+2)-2/(x^2-4*x+3)), (x→1)lim f(x)=?', 'A': r'-1/2', 'W_As': (r'1/2', r'1/4', r'-1/4')}, 
            {'Q': r'f(x)=1-3*x/(x+3), (x→∞)lim f(x)=?', 'A': r'-2', 'W_As': (r'-1', r'0', r'2')}, 
            {'Q': r'a1≠0, a1+a2+...+an=S(n), S(n+1)=2*S(n)+a1, (n→∞)lim an/Sn=?', 'A': r'1/2', 'W_As': (r'0', r'1', r'2')}, 
            {'Q': r'f(x)=∑(1/(3^x)), {x|x∈Z,x≥0}, (x→∞)lim f(x)=?', 'A': r'3/2', 'W_As': (r'5/3', r'2', r'+∞')}, 
            {'Q': r'f(x)=x*(x^(1/2)-x)/(x-1), (x→1)lim f(x)=?', 'A': r'1/2', 'W_As': (r'1/4', r'-1/2', r'-1')}, 
            {'Q': r'a1=1, a(n+1)-an=1/(3^(n+1)), n∈N*, (n→∞)lim an=?', 'A': r'7/6', 'W_As': (r'6/5', r'6/7', r'5/6')}, 
            {'Q': r'(x→∞)lim f(x)=(2*x+(a*(x^2)-2*x+1)/(b*x+2))=2, a+b=?', 'A': r'-1', 'W_As': (r'1', r'0', r'∞')}, 
            {'Q': r'm∈N*,a,b∈R, f(x)=((1+x)^m+a)/x, (x→0)lim f(x)=b, a*b=?', 'A': r'-m', 'W_As': (r'm', r'-1', r'1')}, 
            # 导数
            {'Q': r'f(x, y)=x^2+x*y+y^2+10, (∂y→0)lim ∂f/∂y = ?', 'A': r'x+2y', 'W_As': (r'x^2+x+2y', r'x^2+x+2y+10', r'x+2y+10')}, 
            {'Q': r'f(x)=(x^2)*cos(x), (dx→0)lim df/dx = ?', 'A': r'2*x*cos(x)-(x^2)*sin(x)', 'W_As': (r'-2*x*sin(x)', r'2*x*sin(x)', r'2*x*cos(x)+(x^2)*sin(x)')}, 
            {'Q': r'f(x)=x*sin(x)+x^(1/2), (dx→0)lim df/dx = ?', 'A': r'sin(x)+x*cos(x)+(1/2)*(x^(-1/2))', 'W_As': (r'cos(x)+(1/2)*(x^(-1/2))', r'sin(x)+(1/2)*(x^(-1/2))', r'1+(1/2)*(x^(-1/2))')}, 
            {'Q': r'f(x)=tan(x), (dx→0)lim df/dx = ?', 'A': r'1/cos^2(x)', 'W_As': (r'1', r'0', r'sin(x)')}, 
            {'Q': r'f(x)=sin(x), (dx→0)lim df/dx = ?', 'A': r'cos(x)', 'W_As': (r'1', r'0', r'-sin(x)')}, 
            {'Q': r'f(x)=cos(x), (dx→0)lim df/dx = ?', 'A': r'-sin(x)', 'W_As': (r'1', r'0', r'cos(x)')}, 
            {'Q': r'f(x)=cot(x), (dx→0)lim df/dx = ?', 'A': r'-1/sin^2(x)', 'W_As': (r'1', r'0', r'-tan(x)')}, 
            {'Q': r'f(x)=sec(x), (dx→0)lim df/dx = ?', 'A': r'sec(x)*tan(x)', 'W_As': (r'1/sin(x)', r'1/sec(x)', r'csc(x)')}, 
            {'Q': r'f(x)=csc(x), (dx→0)lim df/dx = ?', 'A': r'-csc(x)*cot(x)', 'W_As': (r'1/cos(x)', r'1/csc(x)', r'sec(x)')},
            {'Q': r'f(x)=e^x, (dx→0)lim df/dx = ?', 'A': r'e^x', 'W_As': (r'x*(e^(x-1))', r'e', r'1/e')}, 
            {'Q': r'f(x)=lnx, (dx→0)lim df/dx = ?', 'A': r'1/x', 'W_As': (r'ln(x-1)', r'x', r'e')}, 
            {'Q': r'f(x, y)=y^x, (∂x→0)lim ∂f/∂x = ?', 'A': r'(y^x)*lny', 'W_As': (r'x*(y^(x-1))', r'y^x', r'(y-1)^x')}, 
            {'Q': r'f(x, y)=y^x, (∂y→0)lim ∂f/∂y = ?', 'A': r'x*(y^(x-1))', 'W_As': (r'(y^x)*lny', r'y^x', r'y^(x-1)')}, 
            {'Q': r'f(x)=x^n, n∈R, (dx→0)lim df/dx = ?', 'A': r'n*(x^(n-1))', 'W_As': (r'x^(n-1)', r'x^n', r'n')}, 
            {'Q': r'f(x)=x^x, (dx→0)lim df/dx = ?', 'A': r'(x^x)*(1+lnx)', 'W_As': (r'(x^x)*lnx', r'x^x', r'x')}, 
            {'Q': r'f(x)=arcsin(x), (dx→0)lim df/dx = ?', 'A': r'1/(1-x^2)^(1/2), |x|<1', 'W_As': (r'-1/(1-x^2)^(1/2), |x|<1', r'-1/(1-x^2)^(1/2), |x|>1', r'1/(1-x^2)^(1/2), |x|>1')},  
            {'Q': r'f(x)=arccos(x), (dx→0)lim df/dx = ?', 'A': r'-1/(1-x^2)^(1/2), |x|<1', 'W_As': (r'1/(1-x^2)^(1/2), |x|>1', r'1/(1-x^2)^(1/2), |x|<1', r'-1/(1-x^2)^(1/2), |x|>1')}, 
            {'Q': r'f(x)=arctan(x), (dx→0)lim df/dx = ?', 'A': r'1/(1+x^2)', 'W_As': (r'-1/(1+x^2)', r'1/(1-x^2)', r'-1/(1-x^2)')}, 
            {'Q': r'f(x)=arccot(x), (dx→0)lim df/dx = ?', 'A': r'-1/(1+x^2)', 'W_As': (r'1/(1+x^2)', r'1/(1-x^2)', r'-1/(1-x^2)')}, 
            {'Q': r'f(x)=arcsec(x), (dx→0)lim df/dx = ?', 'A': r'1/(|x|*((x^2-1)^(1/2))), |x|>1', 'W_As': (r'1/(|x|*((x^2-1)^(1/2))), |x|<1', r'-1/(|x|*((x^2-1)^(1/2))), |x|>1', r'-1/(|x|*((x^2-1)^(1/2))), |x|<1')}, 
            {'Q': r'f(x)=arccsc(x), (dx→0)lim df/dx = ?', 'A': r'-1/(|x|*((x^2-1)^(1/2))), |x|>1', 'W_As': (r'-1/(|x|*((x^2-1)^(1/2))), |x|<1', r'1/(|x|*((x^2-1)^(1/2))), |x|>1', r'1/(|x|*((x^2-1)^(1/2))), |x|<1')}, 
            {'Q': r'f(x)=g(x)±h(x), (dx→0)lim df/dx = ?', 'A': r'g\'(x)±h\'(x)', 'W_As': (r'g\'(x)*h\'(x)', r'g\'(x)/h\'(x)', r'1/g\'(x)±1/h\'(x)')}, 
            {'Q': r'f(x)=g(x)*h(x), (dx→0)lim df/dx = ?', 'A': r'g\'(x)*h(x)+g(x)*h\'(x)', 'W_As': (r'g\'(x)*h\'(x)', r'g\'(x)/h\'(x)', r'2*g\'(x)*h\'(x)')}, 
            {'Q': r'f(x)=g(x)/h(x), h(x)≠0, (dx→0)lim df/dx = ?', 'A': r'(g\'(x)*h(x)-g(x)*h\'(x))/h(x)^2', 'W_As': (r'g\'(x)/h\'(x)', r'g\'(x)*h\'(x)', r'1/g\'(x)±1/h\'(x)')}, 
            {'Q': r'f(x)=1/g(x), g(x)≠0, (dx→0)lim df/dx = ?', 'A': r'-g\'(x)/g(x)^2', 'W_As': (r'-g\'(x)^2', r'1/g\'(x)', r'-g\'(x)')}, 
            {'Q': r'f(x)=g(h(x)), (dx→0)lim df/dx = ?', 'A': r'g\'[h(x)]*h\'(x)', 'W_As': (r'g\'(x)*h\'(x)', r'g\'(x)+h\'(x)', r'g\'(x)*h(x)+g(x)*h\'(x)')}, 
            {'Q': r'f(x, y)=(1+x*y)^y, (∂x→0)lim ∂f/∂x = ?', 'A': r'(y^2)*((1+x*y)^(y-1))', 'W_As': (r'((1+x*y)^y)*((x*y)/(1+x*y))+ln(1+x*y)', r'(1+y)^y', r'1')}, 
            {'Q': r'f(x, y)=(1+x*y)^y, (∂y→0)lim ∂f/∂y = ?', 'A': r'((1+x*y)^y)*((x*y)/(1+x*y))+ln(1+x*y)', 'W_As': (r'(y^2)*((1+x*y)^(y-1))', r'y*((1+x)^(y-1))', r'0')}, 
            {'Q': r'f(x, y)=arccot(y/x), (∂x→0)lim ∂f/∂x = ?', 'A': r'y/((x^2)*(1+(y/x)^2))', 'W_As': (r'arctan(y/x)', r'cot(y/x)', r'-1/(x*(1+(y/x)^2))')}, 
            {'Q': r'f(x, y)=arccot(y/x), (∂y→0)lim ∂f/∂y = ?', 'A': r'-1/(x*(1+(y/x)^2))', 'W_As': (r'arctan(y/x)', r'cot(y/x)', r'y/((x^2)*(1+(y/x)^2))')}, 
            {'Q': r'△f = f(x+△x, y+△y)-f(x, y) = ?', 'A': r'(∂f/∂x)*△x+(∂f/∂y)*△y', 'W_As': (r'(∂f/∂x)+(∂f/∂y)', r'△x+△y', r'(∂f/∂x)*△y+(∂f/∂y)*△x')}, 
            {'Q': r'y=f(x), sin(y)+e^x-x*(y^2)=0, (dx→0)lim df/dx = ?', 'A': r'±(1/2)*(e^(x/2))', 'W_As': (r'e^x', r'sin(x)+e^x-x^3', r'e^(x/2)')}, 
            {'Q': r'f(x, y)=x*y+x/y, (∂x→0)lim ∂f/∂x = ?, (∂y→0)lim ∂f/∂y = ?', 'A': r'∂f/∂x=y+1/y, ∂f/∂y=x-x/y^2', 'W_As': (r'∂f/∂x=x-x/y^2, ∂f/∂y=y+1/y', r'∂f/∂x=2*x, ∂f/∂y=2*y', r'∂f/∂x=y, ∂f/∂y=x')}, 
            {'Q': r'f(x, y)=sin(x*y)+cos^2(x*y), (∂x→0)lim ∂f/∂x = ?, (∂y→0)lim ∂f/∂y = ?', 'A': r'∂f/∂x=-2*y*sin(x*y)*cos(x*y)+y*cos(x*y), ∂f/∂y=-2*x*sin(x*y)*cos(x*y)+x*cos(x*y)', 'W_As': (r'∂f/∂x=1, ∂f/∂y=0', r'∂f/∂x=0, ∂f/∂y=1', r'∂f/∂x=-2*x*sin(x*y)*cos(x*y)+x*cos(x*y), ∂f/∂y=-2*y*sin(x*y)*cos(x*y)+y*cos(x*y)')}, 
            {'Q': r'f(x, y)=(x^2)*ln(x^2+y^2), (∂x→0)lim ∂f/∂x = ?, (∂y→0)lim ∂f/∂y = ?', 'A': r'∂f/∂x=2*x*ln(x^2+y^2)+(2*(x^3))/(x^2+y^2), ∂f/∂y=(2*(x^2)*y)/(x^2+y^2)', 'W_As': (r'∂f/∂x=0, ∂f/∂y=1', r'∂f/∂x=1, ∂f/∂y=0', r'∂f/∂x=(2*(x^2)*y)/(x^2+y^2), ∂f/∂y=2*x*ln(x^2+y^2)+(2*(x^3))/(x^2+y^2)')}, 
            {'Q': r'f(x)=1/x, (dx→0)lim df/dx = ?', 'A': r'-1/(x^2)', 'W_As': (r'1/(x^2)', r'(1/2)*(x^2)', r'(-1/2)*(x^2)')},
            # 积分
            {'Q': r'f(x, y)=x*y, ∬f(x, y)*dx*dy = ?', 'A': r'(1/4)*((x^2)*(y^2))+C1*x+C2, C1,C2∈R', 'W_As': (r'(1/4)*((x^2)*(y^2))+C1*x+C2*y, C1,C2∈R', r'(1/2)*((x^2)*(y^2))+C1+C2*y, C1,C2∈R', r'(x^2)*(y^2)+C1+C2*y, C1,C2∈R')}, 
            {'Q': r'f(x)=sin(x), ∫f(x)*dx = ?', 'A': r'-cos(x)+C, C∈R', 'W_As': (r'cos(x)+C, C∈R', r'-sin(x)+C, C∈R', r'tan(x)+C, C∈R')}, 
            {'Q': r'f(x)=cos(x), ∫f(x)*dx = ?', 'A': r'sin(x)+C, C∈R', 'W_As': (r'-sin(x)+C, C∈R', r'-cos(x)+C, C∈R', r'lnx+C, C∈R')}, 
            {'Q': r'f(x)=tan(x), ∫f(x)*dx = ?', 'A': r'-ln|cos(x)|+C, C∈R', 'W_As': (r'lnx+C, C∈R', r'e^x+C, C∈R', r'ln(sin(x))+C, C∈R')}, 
            {'Q': r'f(x)=cot(x), ∫f(x)*dx = ?', 'A': r'ln|sin(x)|+C, C∈R', 'W_As': (r'lnx+C, C∈R', r'e^x+C, C∈R', r'-ln(cos(x))+C, C∈R')}, 
            {'Q': r'f(x)=-sin(x), ∫f(x)*dx = ?', 'A': r'cos(x)+C, C∈R', 'W_As': (r'-cos(x)+C, C∈R', r'sin(x)+C, C∈R', r'1+tan^2(x)+C, C∈R')}, 
            {'Q': r'f(x)=-cos(x), ∫f(x)*dx = ?', 'A': r'-sin(x)+C, C∈R', 'W_As': (r'sin(x)+C, C∈R', r'cos(x)+C, C∈R', r'1+cot^2(x)+C, C∈R')}, 
            {'Q': r'f(x)=1+tan^2(x), ∫f(x)*dx = ?', 'A': r'tan(x)+C, C∈R', 'W_As': (r'cot(x)+C, C∈R', r'-sin(x)+C, C∈R', r'cos(x)+C, C∈R')}, 
            {'Q': r'f(x)=1/cos^2(x), ∫f(x)*dx = ?', 'A': r'tan(x)+C, C∈R', 'W_As': (r'cot(x)+C, C∈R', r'-sin(x)+C, C∈R', r'cos(x)+C, C∈R')}, 
            {'Q': r'f(x)=-1/sin^2(x), ∫f(x)*dx = ?', 'A': r'cot(x)+C, C∈R', 'W_As': (r'tan(x)+C, C∈R', r'-sin(x)+C, C∈R', r'cos(x)+C, C∈R')}, 
            {'Q': r'f(x)=-1-cot^2(x), ∫f(x)*dx = ?', 'A': r'cot(x)+C, C∈R', 'W_As': (r'tan(x)+C, C∈R', r'-sin(x)+C, C∈R', r'cos(x)+C, C∈R')}, 
            {'Q': r'f(x)=(a*x+b)^n, a,b,n∈R, n≠-1, ∫f(x)*dx = ?', 'A': r'((a*x+b)^(n+1)/(a*(n+1)))+C, C∈R', 'W_As': (r'(1/a)*ln|a*x+b|+C, C∈R', r'(a*x+b)^(n+1)+C, C∈R', r'((a*x+b)^(n+1)/(n+1))+C, C∈R')}, 
            {'Q': r'f(x)=1/(a*x+b), a,b∈R, ∫f(x)*dx = ?', 'A': r'(1/a)*ln|a*x+b|+C, C∈R', 'W_As': (r'((a*x+b)^(n+1)/(a*(n+1)))+C, C∈R', r'a*ln|a*x+b|+C, C∈R', r'((a*x+b)^(n+1)/(n+1))+C, C∈R')}, 
            {'Q': r'f(x)=x/(a*x+b), a,b∈R, ∫f(x)*dx = ?', 'A': r'(1/a^2)*(a*x+b-b*ln|a*x+b|)+C, C∈R', 'W_As': (r'(a^2)*(a*x+b-b*ln|a*x+b|)+C, C∈R', r'(1/b)*ln|(a*x+b)/x|+C, C∈R', r'(-1/b)*ln|(a*x+b)/x|+C, C∈R')}, 
            {'Q': r'f(x)=1/((a*x+b)*x), a,b∈R, ∫f(x)*dx = ?', 'A': r'(-1/b)*ln|(a*x+b)/x|+C, C∈R', 'W_As': (r'(1/b)*ln|(a*x+b)/x|+C, C∈R', r'(a^2)*(a*x+b-b*ln|a*x+b|)+C, C∈R', r'(1/a^2)*(a*x+b-b*ln|a*x+b|)+C, C∈R')}, 
            {'Q': r'f(x)=1/(x^2+a^2), a∈R, ∫f(x)*dx = ?', 'A': r'(arctan(x/a)/a)+C, C∈R', 'W_As': (r'(arccot(x/a)/a)+C, C∈R', r'(tan(x/a)/a)+C, C∈R', r'(cot(x/a)/a)+C, C∈R')}, 
            {'Q': r'f(x)=e^(-a*(x^2)), a∈R, (-∞, +∞)∫f(x)*dx = ?', 'A': r'(π/a)^(1/2)+C, C∈R', 'W_As': (r'-((π/a)^(1/2))+C, C∈R', r'(-π/a)+C, C∈R', r'-(π/a)^2+C, C∈R')}, 
            {'Q': r'f(x)=x*e^(k*x), ∫f(x)*dx = ?', 'A': r'(e^(k*x)*(k*x-1))/(k^2)+C, C∈R', 'W_As': (r'(e^(k*x)*(k*x))/(k^2)+C, C∈R', r'(e^(k*x-1)*(k*x-1))/(k^2)+C, C∈R', r'(e^(k*x-1)*(k*x-1))/(k*x)+C, C∈R')}, 
            {'Q': r'f(x)=a^(k*x), a,k∈R, a>0, a≠1, ∫f(x)*dx = ?', 'A': r'a^(k*x)/(k*lna)+C, C∈R', 'W_As': (r'a^(k*x)/k+C, C∈R', r'a^(k*x-1)/k+C, C∈R', r'a^(k*x)/lna+C, C∈R')}, 
            {'Q': r'f(x)=n*(x^(n-1)), n∈R, ∫f(x)*dx = ?', 'A': r'x^n+C, C∈R', 'W_As': (r'x^(n-1)+C, C∈R', r'(n+1)*(x^n)+C, C∈R', r'(n-1)*(x^n)+C, C∈R')}, 
            {'Q': r'f(x)=sin(lnx), ∫f(x)*dx = ?', 'A': r'(x*(sin(lnx)-cos(lnx))/2)+C, C∈R', 'W_As': (r'-cos(lnx)+C, C∈R', r'-cos(1/x)+C, C∈R', r'(-cos(x)/x)+C, C∈R')}, 
            {'Q': r'f(x)=cos(lnx), ∫f(x)*dx = ?', 'A': r'(x*(sin(lnx)+cos(lnx))/2)+C, C∈R', 'W_As': (r'sin(lnx)+C, C∈R', r'sin(1/x)+C, C∈R', r'(sin(x)/x)+C, C∈R')}, 
            {'Q': r'f(x)=ln(-x), ∫f(x)*dx = ?', 'A': r'x*ln(-x)-x+C, C∈R', 'W_As': (r'(-1/x)+C, C∈R', r'x*lnx-x+C, C∈R', r'-x/lnx-x+C, C∈R')}, 
            {'Q': r'f(x)=lnx, ∫f(x)*dx = ?', 'A': r'x*lnx-x+C, C∈R', 'W_As': (r'1/x+C, C∈R', r'x*ln(-x)-x+C, C∈R', r'x/lnx+x+C, C∈R')}, 
            {'Q': r'f(x)=1/x, ∫f(x)*dx = ?', 'A': r'lnx+C, C∈R', 'W_As': (r'(-1/(x^2))+C, C∈R', r'ln(1/x)+C, C∈R', r'e^(1/x)+C, C∈R')}, 
            {'Q': r'f(x)=e^(k*x), k∈R, ∫f(x)*dx = ?', 'A': r'(e^(k*x))/k+C, C∈R', 'W_As': (r'(e^x)/k+C, C∈R', r'k*e^(k*x)+C, C∈R', r'(e^(k*x-1))/(k-1)+C, C∈R')}, 
            {'Q': r'f(x)=e^(-k*x), k∈R, k≠0, ∫f(x)*dx = ?', 'A': r'(e^(-k*x)/(-k))+C, C∈R', 'W_As': (r'(-e^x/k)+C, C∈R', r'(e^x/k)+C, C∈R', r'((-e^(-k*x))*k)+C, C∈R')}, 
            {'Q': r'f(x)=e^x, ∫f(x)*dx = ?', 'A': r'e^x+C, C∈R', 'W_As': (r'e^(-x)+C, C∈R', r'x*e^(x-1)+C, C∈R', r'e^(x-1)/x+C, C∈R')}, 
            {'Q': r'f(x)=x, ∫f(x)*dx = ?', 'A': r'(1/2)*(x^2)+C, C∈R', 'W_As': (r'x^2+C, C∈R', r'(1/2)*x+C, C∈R', r'2*(x^2)+C, C∈R')}, 
            {'Q': r'f(x)=sin(k*x), ∫f(x)*dx = ?', 'A': r'(-1/k)*cos(k*x)+C, C∈R', 'W_As': (r'(1/k)*sin(k*x)+C, C∈R', r'(-1/k)*ln|cos(k*x)|+C, C∈R', r'(1/k)*ln|sin(k*x)|+C, C∈R')}, 
            {'Q': r'f(x)=cos(k*x), ∫f(x)*dx = ?', 'A': r'(1/k)*sin(k*x)+C, C∈R', 'W_As': (r'(-1/k)*cos(k*x)+C, C∈R', r'(-1/k)*ln|cos(k*x)|+C, C∈R', r'(1/k)*ln|sin(k*x)|+C, C∈R')}, 
            {'Q': r'f(x)=tan(k*x), ∫f(x)*dx = ?', 'A': r'(-1/k)*ln|cos(k*x)|+C, C∈R', 'W_As': (r'(-1/k)*cos(k*x)+C, C∈R', r'(1/k)*sin(k*x)+C, C∈R', r'(1/k)*ln|sin(k*x)|+C, C∈R')}, 
            {'Q': r'f(x)=cot(k*x), ∫f(x)*dx = ?', 'A': r'(1/k)*ln|sin(k*x)|+C, C∈R', 'W_As': (r'(1/k)*sin(k*x)+C, C∈R', r'(-1/k)*ln|cos(k*x)|+C, C∈R', r'(-1/k)*cos(k*x)+C, C∈R')}, 
            # {'Q': r'', 'A': r'', 'W_As': (r'', r'', r'')}, 
        )
    
    def randomQuestion(self):
        i = random.randint(0, len(self.Scattered_Questions)-1)
        return self.Scattered_Questions[i]